
import java.awt.Color;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bhupal Prajapati
 */
public class LoanAssitant extends javax.swing.JFrame {

    /**
     * Creates new form LoanAssitant
     */
    
    
    double loan;
    double interest;
    double month;
    double payment;
    double monthylPayement;
    
   
   
    
    public LoanAssitant() {
        initComponents();
        AnalysisButton.setEnabled(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        balanceField = new javax.swing.JTextField();
        InterestField = new javax.swing.JTextField();
        PaymentField = new javax.swing.JTextField();
        MonthlyField = new javax.swing.JTextField();
        ComputeButton = new javax.swing.JButton();
        AnalysisButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        xPaymentButton = new javax.swing.JButton();
        xMonthButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane2.setViewportView(TextArea);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Assitant");
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Loan Balance:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Interest Rate:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Number Of Payement:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Monthly Payment:");

        balanceField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        InterestField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        PaymentField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        MonthlyField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        ComputeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ComputeButton.setText("Compute Monthly Payment");
        ComputeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputeButtonActionPerformed(evt);
            }
        });

        AnalysisButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AnalysisButton.setText("New Loan Analysis");
        AnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Loan Analysis:");

        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        xPaymentButton.setText("X");
        xPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPaymentButtonActionPerformed(evt);
            }
        });

        xMonthButton.setText("X");
        xMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xMonthButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(AnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton)
                .addGap(190, 190, 190))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balanceField)
                            .addComponent(InterestField)
                            .addComponent(PaymentField)
                            .addComponent(MonthlyField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xMonthButton)
                            .addComponent(xPaymentButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(ComputeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InterestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xPaymentButton))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(MonthlyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xMonthButton))
                        .addGap(38, 38, 38)
                        .addComponent(ComputeButton)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnalysisButton)
                    .addComponent(ExitButton))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 853, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisButtonActionPerformed
        // TODO add your handling code here:
        balanceField.setText("");
        InterestField.setText("");
        PaymentField.setText("");
        TextArea.setText("");
        MonthlyField.setText("");
        AnalysisButton.setEnabled(false);
        ComputeButton.setEnabled(true);
    }//GEN-LAST:event_AnalysisButtonActionPerformed

    private void xPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPaymentButtonActionPerformed
        // TODO add your handling code here:
        boolean ComputButton = true;
        xPaymentButton.setVisible(false);
        xMonthButton.setVisible(true);
        MonthlyField.setEditable(true);
        MonthlyField.setBackground(Color.WHITE);
        MonthlyField.setFocusable(true);
        PaymentField.setEditable(false);
        PaymentField.setBackground(Color.YELLOW);
        PaymentField.setFocusable(false);
        balanceField.requestFocus();
                
                
                
    }//GEN-LAST:event_xPaymentButtonActionPerformed

    private void xMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xMonthButtonActionPerformed
        // TODO add your handling code here:
        boolean ComputButton = false;
        xPaymentButton.setVisible(true);
        xMonthButton.setVisible(false);
        MonthlyField.setEditable(false);
        MonthlyField.setBackground(Color.YELLOW);
        MonthlyField.setFocusable(false);
        PaymentField.setEditable(true); 
        PaymentField.setBackground(Color.WHITE);
        PaymentField.setFocusable(true);
        balanceField.requestFocus();
        ComputeButton.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_xMonthButtonActionPerformed

    private void ComputeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputeButtonActionPerformed
        // TODO add your handling code here:
        String iBalance = String.format(balanceField.getText());
        String iMonthlyPayment = String.format(MonthlyField.getText());
//        String iInterest = String.format(InterestField.getText());
//        String iMonth = String.format(PaymentField.getText());
        
        if( balanceField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You Must Enter Amount of Balance)","Loan System",JOptionPane.INFORMATION_MESSAGE);
        }else{
            loan = Double.parseDouble(balanceField.getText());
            String Balance = String.format(balanceField.getText());
              
        }
        
         if( InterestField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You Must Enter Amount of Interest)","Loan System",JOptionPane.INFORMATION_MESSAGE);
        }else{
            interest = Double.parseDouble(InterestField.getText());
            String iInterest = String.format(InterestField.getText());
            
            
        }
         
          if( PaymentField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You Must Enter Amount of Payement)","Loan System",JOptionPane.INFORMATION_MESSAGE);
        }else{
            month = Double.parseDouble(PaymentField.getText());
            String iMonth = String.format(PaymentField.getText());
            
//            MonthylPayement
//                    month
//                    
        }
          payment = loan + ((loan*interest)/100);
          monthylPayement = payment/ month;
          String PayMonth = String.format("%.2f", monthylPayement);
          MonthlyField.setText(PayMonth);
          textArea.append("\t\n Loan Assitant Project:\n\n" +
                  " Amount Of Loan:\t\t $"                     + loan +
                  "\n Interest Rate:\t\t"                     + interest+
                  "%"+"\n No Of Per Month Payment:\t\t"+ month+ 
                    " Months" +  "\n Payment Per Month:\t\t $"+monthylPayement+
                  "\n Total Loan Payment:\t\t $"              +payment+
                  "\n\n Thanks" );
          
          AnalysisButton.setEnabled(true);
          ComputeButton.setEnabled(false);
          


        
    }//GEN-LAST:event_ComputeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAssitant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAssitant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAssitant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAssitant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanAssitant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalysisButton;
    private javax.swing.JButton ComputeButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField InterestField;
    private javax.swing.JTextField MonthlyField;
    private javax.swing.JTextField PaymentField;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JTextField balanceField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textArea;
    private javax.swing.JButton xMonthButton;
    private javax.swing.JButton xPaymentButton;
    // End of variables declaration//GEN-END:variables
}
